#ifndef __CHARACTER_MOVE_DIRECTIONS_
#define __CHARACTER_MOVE_DIRECTIONS_

#define CHARACTER_MOVE_DOWN 1
#define CHARACTER_MOVE_UP 2
#define CHARACTER_MOVE_LEFT 3
#define CHARACTER_MOVE_RIGHT 4

#endif
